###################################################################
### DOCTOR

### register | OK
POST http://localhost:8080/doctor/register
Content-Type: application/json

{
  "firstName": "james",
  "lastName": "adam",
  "phoneNumber": "01010931887",
  "nationalId": "29212392313",
  "dateOfBirth": "1997-07-16",
  "email": "z1@aa.com",
  "spec": "cardiology",
  "password": "xcdz"
}

### all doctors | OK
GET http://localhost:8080/doctor/all

### one | OK
GET http://localhost:8080/doctor/one/2

### get by specialization

GET http://localhost:8080/doctor/specialization/1

### edit  | OK
PUT http://localhost:8080/doctor/9
Content-Type: application/json

{
  "workingHoursStart": "05:00",
  "workingHoursEnd": "23:00",
  "bookingDuration": 0.25
}

### delete  | OK
DELETE http://localhost:8080/doctor/3

###########################################################################
### PATIENT

### register
POST http://localhost:8080/user/register
Content-Type: application/json

{
  "firstName": "james",
  "lastName": "adam",
  "phoneNumber": "01010931887",
  "nationalId": "921332393213",
  "dateOfBirth": "1997-07-16",
  "email": "r6@z.com",
  "password": "xcdz"
}

### update  | OK
PUT http://localhost:8080/user/12
Content-Type: application/json

{
  "firstName": "jamesxxx",
  "lastName": "bbbbb",
  "phoneNumber": "01018888888888888887"
}

### delete | OK
DELETE http://localhost:8080/user/12

### login
POST http://localhost:8080/login
Content-Type: application/json

{
  "email": "r6@z.com",
  "password": "xcdz"
}

###########################################################################

### RESERVATIONS

### patient reservations | OK
GET http://localhost:8080/book/patient/2

### doctor reservations | OK
GET http://localhost:8080/book/doctor/9

### book | OK

POST http://localhost:8080/book
Content-Type: application/json

{
  "doctorId": 9,
  "patientId": 2,
  "day": "2023-12-24",
  "start": "05:00",
  "end": "05:15"
}

### slots | OK

GET http://localhost:8080/book/availble_slots/9

### delete | OK
DELETE http://localhost:8080/book/25
