GET http://localhost:8080/book/doctor/1
###

POST http://localhost:8080/book
Content-Type: application/json

{
    "doctorId": 1,
    "patientId": 1,
    "day": "2023-12-06",
    "start": "06:00",
    "end": "07:00"
}

###

GET http://localhost:8080/doctor/all

###

PUT http://localhost:8080/doctor/edit/1
Content-Type: application/json

{
    "workingHoursStart": "06:00",
    "workingHoursEnd": "09:00",
    "bookingDuration": 1
}

###

GET http://localhost:8080/book/availble_slots/1

###

DELETE http://localhost:8080/book/3
###

GET http://localhost:8080/doctor/all
###
DELETE http://localhost:8080/doctor/8
###
# rafadoctor69191@zz.com
PUT http://localhost:8080/doctor/1
Content-Type: application/json

{
   "specializationId": NULL
}